Environment Configuration Management in Maven
=============================================

=== The Configuration Management Problem

By default, maven produces artifacts that contain both the resources and the classes, binaries, and static resources.

How to produce artifacts that can be deployed to multiple environments in maven?

=== Potential Solutions

The solutions we explore here work around a scenario that requires:

* A generic mechanism that can be used across many services/apps/projects
* The outputs of this configuration management scheme or mechanism is a set of packages, some for the binary artifacts (i.e. environment agnostic), and one or more for each environment we intend to deploy the application to.

=== Mechanism 1 : Manual

Create a configuration jar by replacing values manually then running some commands to jar the file. E.g.

[source,bash]
----
# for replacement
$ vim
$ sed

# for compressing
$ jar cvf
$ zip
$ gzip

# for deploying
$ mvn deploy:deploy-file [some other params]
$ curl [some other params]
----

* Cons:

** does not scale
** time consuming
** error prone
** non-repeatable

* Pros:

** should be considered in exceptional circumstances
** very flexible


=== Mechanism 2: Maven Profiles

Create a profile for each environment, where an ${env} variable is set to control the filtering of resources. Link to example?

* Cons:

** Complex to configure
** Difficult to maintain
** Cannot produce all environments with single command
** Poses many questions with regard to deployment
** Produces a different artifact depending on the profile chosen, which goes against maven’s intended use of profiles.
** Does not separate configuration from binaries (unless we complicate the pom even more)

* Pros:

** Profiles are an integral part of maven: no need to introduce new technologies, languages, tools, plugins, etc)
** Good for environments where build and deployments happen on the same environment for example

=== Mechanism 3: Assembly Descriptor

Create an assembly descriptor for each environment, then associate each of these descriptors in the pom with a filtering location. Link to example?

* Cons:

** Complex to configure
** Difficult to maintain
** Cannot produce all environments with single command
** Poses many questions with regard to deployment
** Produces a different artifact depending on the profile chosen, which goes against maven’s intended use of profiles.
** Does not separate configuration from binaries (unless we even more complicate the pom)

* Pros:

** Profiles are an integral part of maven: no need to introduce new technologies, languages, tools, plugins, etc)